# 1) ჩამოწერეთ and და or ოპერაციის ყველა სესაძლო შემთხვევა (სულ 8)
print(False or False)
print(True or False)
print(True or True)
print(True and False)
print(False and False)
print(True and True)
print(True or Flase and True)
print(True and False or False)